# Generated by Django 2.2 on 2022-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181201_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rfid',
            field=models.TextField(default=1111111111),
            preserve_default=False,
        ),
    ]
