# Generated by Django 2.2 on 2022-09-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_contact_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='rfid',
        ),
    ]
