# Generated by Django 2.2 on 2022-09-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_contact_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rfid',
            field=models.TextField(default=1111111111),
            preserve_default=False,
        ),
    ]
